#!/usr/bin/env python3
"""Generate secrets.h for every sketch under arduino_src/ from config.json.

A "sketch" is any immediate subdirectory of arduino_src/ that contains a
.ino file. The same secrets.h content is written into each sketch directory
so that sketches share WiFi credentials and any common configuration values.

Run from repo root:
    python3 scripts/gen_secrets.py [--config config.json] [--src-dir arduino_src]
"""
import argparse
import json
import sys
from pathlib import Path


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def find_sketch_dirs(src_dir: Path) -> list[Path]:
    out: list[Path] = []
    for child in sorted(src_dir.iterdir()):
        if not child.is_dir():
            continue
        if any(p.suffix == ".ino" for p in child.iterdir()):
            out.append(child)
    return out


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(repo_root / "config.json"))
    parser.add_argument("--src-dir", default=str(repo_root / "arduino_src"))
    args = parser.parse_args()

    config_path = Path(args.config)
    src_dir = Path(args.src_dir)

    with config_path.open("r", encoding="utf-8") as f:
        cfg = json.load(f)

    ssid = cfg["wifi"]["ssid"]
    password = cfg["wifi"]["password"]
    port = int(cfg["server"]["port"])
    rate_hz = int(cfg["control"]["rate_hz"])
    failsafe_ms = int(cfg["control"]["failsafe_ms"])
    max_motor = int(cfg["motor"]["max_motor"])

    camera_cfg = cfg.get("camera", {})
    announce_port = int(camera_cfg.get("announce_port", 4211))
    announce_interval_ms = int(camera_cfg.get("announce_interval_ms", 1000))

    if not 1 <= port <= 65535:
        print(f"server.port out of range: {port}", file=sys.stderr)
        return 1
    if not 1 <= rate_hz <= 200:
        print(f"control.rate_hz out of range: {rate_hz}", file=sys.stderr)
        return 1
    if not 0 <= max_motor <= 127:
        print(f"motor.max_motor out of range: {max_motor}", file=sys.stderr)
        return 1
    if not 1 <= announce_port <= 65535:
        print(f"camera.announce_port out of range: {announce_port}", file=sys.stderr)
        return 1
    if not 50 <= announce_interval_ms <= 60000:
        print(
            f"camera.announce_interval_ms out of range: {announce_interval_ms}",
            file=sys.stderr,
        )
        return 1

    content = (
        "#pragma once\n"
        "// Generated by scripts/gen_secrets.py from config.json. Do not edit by hand.\n"
        f'#define WIFI_SSID "{c_escape(ssid)}"\n'
        f'#define WIFI_PASSWORD "{c_escape(password)}"\n'
        f"#define SERVER_PORT {port}\n"
        f"#define CONTROL_RATE_HZ {rate_hz}\n"
        f"#define FAILSAFE_MS {failsafe_ms}\n"
        f"#define MAX_MOTOR {max_motor}\n"
        f"#define CAMERA_ANNOUNCE_PORT {announce_port}\n"
        f"#define CAMERA_ANNOUNCE_INTERVAL_MS {announce_interval_ms}\n"
    )

    sketch_dirs = find_sketch_dirs(src_dir)
    if not sketch_dirs:
        print(f"no sketches found under {src_dir}", file=sys.stderr)
        return 1

    for sketch in sketch_dirs:
        out_path = sketch / "secrets.h"
        out_path.write_text(content, encoding="utf-8")
        print(f"wrote {out_path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
