#!/usr/bin/env python3
"""Generate src/roverc_server/secrets.h from config.json.

Run from repo root:
    python3 scripts/gen_secrets.py [--config config.json] [--out src/roverc_server/secrets.h]
"""
import argparse
import json
import sys
from pathlib import Path


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(repo_root / "config.json"))
    parser.add_argument(
        "--out", default=str(repo_root / "src" / "roverc_server" / "secrets.h")
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    out_path = Path(args.out)

    with config_path.open("r", encoding="utf-8") as f:
        cfg = json.load(f)

    ssid = cfg["wifi"]["ssid"]
    password = cfg["wifi"]["password"]
    port = int(cfg["server"]["port"])
    rate_hz = int(cfg["control"]["rate_hz"])
    failsafe_ms = int(cfg["control"]["failsafe_ms"])
    max_motor = int(cfg["control"]["max_motor"])

    if not 1 <= port <= 65535:
        print(f"server.port out of range: {port}", file=sys.stderr)
        return 1
    if not 1 <= rate_hz <= 200:
        print(f"control.rate_hz out of range: {rate_hz}", file=sys.stderr)
        return 1
    if not 0 <= max_motor <= 127:
        print(f"control.max_motor out of range: {max_motor}", file=sys.stderr)
        return 1

    content = (
        "#pragma once\n"
        "// Generated by scripts/gen_secrets.py from config.json. Do not edit by hand.\n"
        f'#define WIFI_SSID "{c_escape(ssid)}"\n'
        f'#define WIFI_PASSWORD "{c_escape(password)}"\n'
        f"#define SERVER_PORT {port}\n"
        f"#define CONTROL_RATE_HZ {rate_hz}\n"
        f"#define FAILSAFE_MS {failsafe_ms}\n"
        f"#define MAX_MOTOR {max_motor}\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"wrote {out_path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
